/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventoryapp.app.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author THINKPAD X240
 */
public class MenuView extends javax.swing.JFrame {

    private JInternalFrame currentFrame;

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();

//        addComponentListener(new java.awt.event.ComponentAdapter() {
//            @Override
//            public void componentResized(java.awt.event.ComponentEvent evt) {
//
//                jPanel1.setBounds(0, 0, 250, getHeight());
//
//                jDesktopPane2.setBounds(
//                        250,
//                        0,
//                        getWidth() - 250,
//                        getHeight()
//                );
//
//                if (currentFrame != null) {
//                    currentFrame.setBounds(
//                            0,
//                            0,
//                            jDesktopPane2.getWidth(),
//                            jDesktopPane2.getHeight()
//                    );
//                }
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        llblMenuLainnya = new javax.swing.JLabel();
        btnBMasuk = new javax.swing.JButton();
        lblJudul = new javax.swing.JLabel();
        btnBarang = new javax.swing.JButton();
        btnKategori = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        lblMenuMaster = new javax.swing.JLabel();
        lblMenuTraksaksi = new javax.swing.JLabel();
        btnBKeluar = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        lblNamaAkun = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STORAGE SYSTEM APP");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        llblMenuLainnya.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        llblMenuLainnya.setForeground(new java.awt.Color(240, 240, 240));
        llblMenuLainnya.setText("Lainnya");
        jPanel1.add(llblMenuLainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, -1, -1));

        btnBMasuk.setText("Barang Masuk");
        btnBMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBMasukActionPerformed(evt);
            }
        });
        jPanel1.add(btnBMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 180, 40));

        lblJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(240, 240, 240));
        lblJudul.setText("Storage System");
        jPanel1.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        btnBarang.setText("Barang");
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });
        jPanel1.add(btnBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 40));

        btnKategori.setText("Kategori");
        btnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(btnKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, 40));

        btnSupplier.setText("Supplier");
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, 40));

        btnPelanggan.setText("Pelanggan");
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });
        jPanel1.add(btnPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 40));

        lblMenuMaster.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMenuMaster.setForeground(new java.awt.Color(240, 240, 240));
        lblMenuMaster.setText("Master Data");
        jPanel1.add(lblMenuMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        lblMenuTraksaksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMenuTraksaksi.setForeground(new java.awt.Color(240, 240, 240));
        lblMenuTraksaksi.setText("Transaksi");
        jPanel1.add(lblMenuTraksaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        btnBKeluar.setText("Barang Keluar");
        btnBKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 180, 40));

        btnLaporan.setText("Laporan");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        jPanel1.add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 180, 40));

        lblNamaAkun.setForeground(new java.awt.Color(240, 240, 240));
        lblNamaAkun.setText("Administartor");
        jPanel1.add(lblNamaAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 700));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 970, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBMasukActionPerformed
        // TODO add your handling code here:
        bukaMenu(new BarangMasukView());
    }//GEN-LAST:event_btnBMasukActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        bukaMenu(new BarangView());
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriActionPerformed
        // TODO add your handling code here:
        bukaMenu(new KategoriView());
    }//GEN-LAST:event_btnKategoriActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        // TODO add your handling code here:
        bukaMenu(new SupplierView());
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        // TODO add your handling code here:
        bukaMenu(new PelangganView());
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnBKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBKeluarActionPerformed
        // TODO add your handling code here:
        bukaMenu(new BarangKeluarView());
    }//GEN-LAST:event_btnBKeluarActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void bukaMenu(JInternalFrame frame) {

        jDesktopPane2.removeAll();
        jDesktopPane2.repaint();

        currentFrame = frame;

        frame.setBounds(0, 0,
                jDesktopPane2.getWidth(),
                jDesktopPane2.getHeight());

        jDesktopPane2.add(frame);
        frame.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBKeluar;
    private javax.swing.JButton btnBMasuk;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnKategori;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblMenuMaster;
    private javax.swing.JLabel lblMenuTraksaksi;
    private javax.swing.JLabel lblNamaAkun;
    private javax.swing.JLabel llblMenuLainnya;
    // End of variables declaration//GEN-END:variables
}
